window.activosExcel = [
  {
    codigo: "20001",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "2.5x1.3x7.4 m",
    serie: "",
    area: "Gerencia",
    ceco: "Pedro Huamán 10",
    estado: "Regular",
  },
  {
    codigo: "20002",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "1.7x7.0x7.3 m",
    serie: "",
    area: "Producción",
    ceco: "Paola Ramos 22",
    estado: "Malo",
  },
  {
    codigo: "20003",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "Sistemas",
    ceco: "Lucía Flores 47",
    estado: "Malo",
  },
  {
    codigo: "20004",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 845",
    color: "Marrón",
    material: "",
    medidas: "15'",
    serie: "SN730756384",
    area: "Gerencia",
    ceco: "Marco Espinoza 33",
    estado: "Regular",
  },
  {
    codigo: "20005",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.9x4.6x6.8 m",
    serie: "",
    area: "Administración",
    ceco: "Marco Espinoza 33",
    estado: "Regular",
  },
  {
    codigo: "20006",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Madera",
    medidas: "2.3x3.0x7.4 m",
    serie: "",
    area: "Producción",
    ceco: "Miguel Quispe 29",
    estado: "Malo",
  },
  {
    codigo: "20007",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Administración",
    ceco: "Lucía Flores 31",
    estado: "Regular",
  },
  {
    codigo: "20008",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Administración",
    ceco: "Silvia Benavides",
    estado: "Regular",
  },
  {
    codigo: "20009",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "Gerencia",
    ceco: "Patricia Silva 46",
    estado: "Regular",
  },
  {
    codigo: "20010",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "Logística",
    ceco: "Víctor Palacios",
    estado: "Regular",
  },
  {
    codigo: "20011",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 965",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN485804992",
    area: "Gerencia",
    ceco: "Carlos Rivas 62",
    estado: "Bueno",
  },
  {
    codigo: "20012",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 366",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN793791754",
    area: "Gerencia",
    ceco: "Miguel Quispe 85",
    estado: "Bueno",
  },
  {
    codigo: "20013",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 257",
    color: "Marrón",
    material: "",
    medidas: "19'",
    serie: "SN256205394",
    area: "Producción",
    ceco: "Daniel León 37",
    estado: "Bueno",
  },
  {
    codigo: "20014",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Madera",
    medidas: "2.5x5.1x6.8 m",
    serie: "",
    area: "Administración",
    ceco: "Carmen Valdez 92",
    estado: "Malo",
  },
  {
    codigo: "20015",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 404",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN506746880",
    area: "Logística",
    ceco: "Silvia Benavides",
    estado: "Regular",
  },
  {
    codigo: "20016",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 261",
    color: "Marrón",
    material: "",
    medidas: "15'",
    serie: "SN518039566",
    area: "Gerencia",
    ceco: "Daniel León 37",
    estado: "Bueno",
  },
  {
    codigo: "20017",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "1.7x1.5x8.4 m",
    serie: "",
    area: "Sistemas",
    ceco: "Luis Paredes 34",
    estado: "Malo",
  },
  {
    codigo: "20018",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Madera",
    medidas: "1.9x6.2x2.4 m",
    serie: "",
    area: "Sistemas",
    ceco: "Paola Ramos 22",
    estado: "Malo",
  },
  {
    codigo: "20019",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "RRHH",
    ceco: "Miguel Quispe 85",
    estado: "Bueno",
  },
  {
    codigo: "20020",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "1.8x7.0x2.6 m",
    serie: "",
    area: "Administración",
    ceco: "Carlos Rivas 62",
    estado: "Regular",
  },
  {
    codigo: "20021",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 479",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN203056023",
    area: "Sistemas",
    ceco: "Daniel León 37",
    estado: "Regular",
  },
  {
    codigo: "20022",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Madera",
    medidas: "1.0x5.4x1.2 m",
    serie: "",
    area: "Sistemas",
    ceco: "Lucía Flores 31",
    estado: "Regular",
  },
  {
    codigo: "20023",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "RRHH",
    ceco: "Miguel Quispe 72",
    estado: "Bueno",
  },
  {
    codigo: "20024",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 830",
    color: "Blanco",
    material: "",
    medidas: "15'",
    serie: "SN688430404",
    area: "Gerencia",
    ceco: "Pedro Huamán 14",
    estado: "Bueno",
  },
  {
    codigo: "20025",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "RRHH",
    ceco: "Juan Cruz Saldaña 6",
    estado: "Malo",
  },
  {
    codigo: "20026",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.1x1.8x5.5 m",
    serie: "",
    area: "RRHH",
    ceco: "Ana Gómez 57",
    estado: "Bueno",
  },
  {
    codigo: "20027",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "RRHH",
    ceco: "Andrea Ruiz 20",
    estado: "Bueno",
  },
  {
    codigo: "20028",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Sistemas",
    ceco: "Luis Paredes 34",
    estado: "Regular",
  },
  {
    codigo: "20029",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Madera",
    medidas: "1.9x7.7x4.0 m",
    serie: "",
    area: "Gerencia",
    ceco: "Carlos Rivas 70",
    estado: "Bueno",
  },
  {
    codigo: "20030",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 635",
    color: "Gris",
    material: "",
    medidas: "25'",
    serie: "SN454528058",
    area: "Gerencia",
    ceco: "Lucía Flores 31",
    estado: "Regular",
  },
  {
    codigo: "20031",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 918",
    color: "Blanco",
    material: "",
    medidas: "23'",
    serie: "SN409191001",
    area: "Gerencia",
    ceco: "Juan Cruz Saldaña 57",
    estado: "Bueno",
  },
  {
    codigo: "20032",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Madera",
    medidas: "1.7x0.1x7.4 m",
    serie: "",
    area: "Logística",
    ceco: "Carlos Rivas 70",
    estado: "Regular",
  },
  {
    codigo: "20033",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 993",
    color: "Marrón",
    material: "",
    medidas: "15'",
    serie: "SN687931306",
    area: "Administración",
    ceco: "Carlos Rivas 62",
    estado: "Bueno",
  },
  {
    codigo: "20034",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 459",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN162642722",
    area: "Sistemas",
    ceco: "Rosa Mendoza 45",
    estado: "Malo",
  },
  {
    codigo: "20035",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Madera",
    medidas: "1.4x5.9x4.3 m",
    serie: "",
    area: "Gerencia",
    ceco: "Ana Gómez 57",
    estado: "Malo",
  },
  {
    codigo: "20036",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 696",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN964399758",
    area: "Logística",
    ceco: "Paola Ramos 22",
    estado: "Malo",
  },
  {
    codigo: "20037",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.5x2.6x7.3 m",
    serie: "",
    area: "Producción",
    ceco: "Carlos Rivas 18",
    estado: "Malo",
  },
  {
    codigo: "20038",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "2.6x5.9x4.3 m",
    serie: "",
    area: "Administración",
    ceco: "Ana Gómez 57",
    estado: "Regular",
  },
  {
    codigo: "20039",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.0x4.8x3.2 m",
    serie: "",
    area: "Sistemas",
    ceco: "Paola Ramos 22",
    estado: "Malo",
  },
  {
    codigo: "20040",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "Sistemas",
    ceco: "Miguel Quispe 72",
    estado: "Malo",
  },
  {
    codigo: "20041",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 811",
    color: "Blanco",
    material: "",
    medidas: "18'",
    serie: "SN934575011",
    area: "Logística",
    ceco: "Paola Ramos 22",
    estado: "Malo",
  },
  {
    codigo: "20042",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Metal",
    medidas: "1.8x4.5x4.1 m",
    serie: "",
    area: "Gerencia",
    ceco: "Lucía Flores 31",
    estado: "Regular",
  },
  {
    codigo: "20043",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 946",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN650097507",
    area: "Sistemas",
    ceco: "Silvia Benavides",
    estado: "Regular",
  },
  {
    codigo: "20044",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.2x5.4x8.2 m",
    serie: "",
    area: "RRHH",
    ceco: "Lucía Flores 31",
    estado: "Malo",
  },
  {
    codigo: "20045",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 257",
    color: "Marrón",
    material: "",
    medidas: "22'",
    serie: "SN179109037",
    area: "Sistemas",
    ceco: "Pedro Huamán 10",
    estado: "Regular",
  },
  {
    codigo: "20046",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "1.3x3.8x2.4 m",
    serie: "",
    area: "Producción",
    ceco: "Carlos Rivas 70",
    estado: "Malo",
  },
  {
    codigo: "20047",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Metal",
    medidas: "2.3x5.9x1.1 m",
    serie: "",
    area: "Gerencia",
    ceco: "María Torres 12",
    estado: "Bueno",
  },
  {
    codigo: "20048",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 359",
    color: "Negro",
    material: "",
    medidas: "18'",
    serie: "SN589835785",
    area: "Gerencia",
    ceco: "Miguel Quispe 29",
    estado: "Malo",
  },
  {
    codigo: "20049",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 471",
    color: "Blanco",
    material: "",
    medidas: "23'",
    serie: "SN111189790",
    area: "Sistemas",
    ceco: "Patricia Silva 9",
    estado: "Regular",
  },
  {
    codigo: "20050",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 806",
    color: "Gris",
    material: "",
    medidas: "23'",
    serie: "SN935676355",
    area: "Logística",
    ceco: "Paola Ramos 22",
    estado: "Bueno",
  },
  {
    codigo: "20051",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Mixto",
    medidas: "1.8x7.0x7.8 m",
    serie: "",
    area: "Sistemas",
    ceco: "Juan Cruz Saldaña 6",
    estado: "Regular",
  },
  {
    codigo: "20052",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "Gerencia",
    ceco: "Miguel Quispe 72",
    estado: "Bueno",
  },
  {
    codigo: "20053",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.0x1.9x0.0 m",
    serie: "",
    area: "Logística",
    ceco: "Lucía Flores 31",
    estado: "Regular",
  },
  {
    codigo: "20054",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 646",
    color: "Negro",
    material: "",
    medidas: "18'",
    serie: "SN950514912",
    area: "Gerencia",
    ceco: "Andrea Ruiz 20",
    estado: "Regular",
  },
  {
    codigo: "20055",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.7x5.9x3.9 m",
    serie: "",
    area: "Gerencia",
    ceco: "María Torres 35",
    estado: "Bueno",
  },
  {
    codigo: "20056",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.4x5.7x3.4 m",
    serie: "",
    area: "Producción",
    ceco: "Ana Gómez 57",
    estado: "Malo",
  },
  {
    codigo: "20057",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "2.5x6.8x7.2 m",
    serie: "",
    area: "Producción",
    ceco: "Miguel Quispe 29",
    estado: "Bueno",
  },
  {
    codigo: "20058",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "2.6x6.4x3.7 m",
    serie: "",
    area: "Sistemas",
    ceco: "Luis Paredes 34",
    estado: "Regular",
  },
  {
    codigo: "20059",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 798",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN881983590",
    area: "Sistemas",
    ceco: "Patricia Silva 9",
    estado: "Malo",
  },
  {
    codigo: "20060",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "RRHH",
    ceco: "Lucía Flores 31",
    estado: "Regular",
  },
  {
    codigo: "20061",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "1.4x6.9x0.0 m",
    serie: "",
    area: "Gerencia",
    ceco: "José Ramírez",
    estado: "Regular",
  },
  {
    codigo: "20062",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 136",
    color: "Blanco",
    material: "",
    medidas: "26'",
    serie: "SN312433149",
    area: "Producción",
    ceco: "Patricia Silva 46",
    estado: "Bueno",
  },
  {
    codigo: "20063",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 636",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN946027196",
    area: "Producción",
    ceco: "Óscar Medina 74",
    estado: "Malo",
  },
  {
    codigo: "20064",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Madera",
    medidas: "2.8x5.5x4.9 m",
    serie: "",
    area: "Producción",
    ceco: "Rosa Mendoza 45",
    estado: "Malo",
  },
  {
    codigo: "20065",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Madera",
    medidas: "1.8x7.3x1.8 m",
    serie: "",
    area: "Logística",
    ceco: "Patricia Silva 9",
    estado: "Regular",
  },
  {
    codigo: "20066",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Gerencia",
    ceco: "Miguel Quispe 72",
    estado: "Bueno",
  },
  {
    codigo: "20067",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 116",
    color: "Blanco",
    material: "",
    medidas: "23'",
    serie: "SN465068353",
    area: "RRHH",
    ceco: "Paola Ramos 22",
    estado: "Malo",
  },
  {
    codigo: "20068",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "Producción",
    ceco: "Patricia Silva 9",
    estado: "Malo",
  },
  {
    codigo: "20069",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 688",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN436177452",
    area: "Administración",
    ceco: "Elena Chávez 85",
    estado: "Malo",
  },
  {
    codigo: "20070",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "1.2x6.6x4.0 m",
    serie: "",
    area: "RRHH",
    ceco: "María Torres 35",
    estado: "Malo",
  },
  {
    codigo: "20071",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 253",
    color: "Blanco",
    material: "",
    medidas: "26'",
    serie: "SN268414645",
    area: "Administración",
    ceco: "Marco Espinoza 33",
    estado: "Bueno",
  },
  {
    codigo: "20072",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 785",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN500184450",
    area: "Administración",
    ceco: "Carlos Rivas 70",
    estado: "Bueno",
  },
  {
    codigo: "20073",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "Producción",
    ceco: "Carmen Valdez 92",
    estado: "Regular",
  },
  {
    codigo: "20074",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "2.5x1.7x7.1 m",
    serie: "",
    area: "Sistemas",
    ceco: "Hugo Cárdenas",
    estado: "Malo",
  },
  {
    codigo: "20075",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 909",
    color: "Marrón",
    material: "",
    medidas: "20'",
    serie: "SN949635982",
    area: "Producción",
    ceco: "Lucía Flores 31",
    estado: "Bueno",
  },
  {
    codigo: "20076",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "1.6x7.4x8.6 m",
    serie: "",
    area: "Gerencia",
    ceco: "Patricia Silva 9",
    estado: "Bueno",
  },
  {
    codigo: "20077",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 248",
    color: "Negro",
    material: "",
    medidas: "24'",
    serie: "SN803188953",
    area: "Logística",
    ceco: "Miguel Quispe 29",
    estado: "Malo",
  },
  {
    codigo: "20078",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 908",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN156072351",
    area: "Administración",
    ceco: "Víctor Palacios",
    estado: "Regular",
  },
  {
    codigo: "20079",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "1.9x7.4x6.4 m",
    serie: "",
    area: "Producción",
    ceco: "Lucía Flores 42",
    estado: "Regular",
  },
  {
    codigo: "20080",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "1.1x2.0x5.9 m",
    serie: "",
    area: "Gerencia",
    ceco: "Juan Cruz Saldaña 6",
    estado: "Regular",
  },
  {
    codigo: "20081",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.2x6.4x5.3 m",
    serie: "",
    area: "Producción",
    ceco: "Pedro Huamán 14",
    estado: "Malo",
  },
  {
    codigo: "20082",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "1.9x6.6x3.9 m",
    serie: "",
    area: "Administración",
    ceco: "Carlos Rivas 70",
    estado: "Bueno",
  },
  {
    codigo: "20083",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "1.4x2.0x5.4 m",
    serie: "",
    area: "RRHH",
    ceco: "Luis Paredes 34",
    estado: "Malo",
  },
  {
    codigo: "20084",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 368",
    color: "Blanco",
    material: "",
    medidas: "17'",
    serie: "SN804960527",
    area: "Administración",
    ceco: "Daniel León 29",
    estado: "Regular",
  },
  {
    codigo: "20085",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 467",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN589145356",
    area: "Gerencia",
    ceco: "Silvia Benavides",
    estado: "Bueno",
  },
  {
    codigo: "20086",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "2.0x2.6x6.1 m",
    serie: "",
    area: "Logística",
    ceco: "Daniel León 37",
    estado: "Malo",
  },
  {
    codigo: "20087",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 875",
    color: "Gris",
    material: "",
    medidas: "16'",
    serie: "SN285899253",
    area: "RRHH",
    ceco: "Silvia Benavides",
    estado: "Regular",
  },
  {
    codigo: "20088",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 156",
    color: "Gris",
    material: "",
    medidas: "23'",
    serie: "SN579313973",
    area: "RRHH",
    ceco: "Lucía Flores 31",
    estado: "Regular",
  },
  {
    codigo: "20089",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 571",
    color: "Gris",
    material: "",
    medidas: "21'",
    serie: "SN466431389",
    area: "Sistemas",
    ceco: "Víctor Palacios",
    estado: "Malo",
  },
  {
    codigo: "20090",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 545",
    color: "Negro",
    material: "",
    medidas: "20'",
    serie: "SN230789065",
    area: "RRHH",
    ceco: "Hugo Cárdenas",
    estado: "Malo",
  },
  {
    codigo: "20091",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 115",
    color: "Blanco",
    material: "",
    medidas: "25'",
    serie: "SN566670598",
    area: "Gerencia",
    ceco: "Elena Chávez 85",
    estado: "Regular",
  },
  {
    codigo: "20092",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 182",
    color: "Negro",
    material: "",
    medidas: "22'",
    serie: "SN481501259",
    area: "Producción",
    ceco: "Lucía Flores 47",
    estado: "Bueno",
  },
  {
    codigo: "20093",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 304",
    color: "Blanco",
    material: "",
    medidas: "19'",
    serie: "SN173152709",
    area: "RRHH",
    ceco: "Óscar Medina 1",
    estado: "Malo",
  },
  {
    codigo: "20094",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "RRHH",
    ceco: "Silvia Benavides",
    estado: "Malo",
  },
  {
    codigo: "20095",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 240",
    color: "Negro",
    material: "",
    medidas: "19'",
    serie: "SN266049211",
    area: "Administración",
    ceco: "Juan Cruz Saldaña 57",
    estado: "Bueno",
  },
  {
    codigo: "20096",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 331",
    color: "Marrón",
    material: "",
    medidas: "21'",
    serie: "SN185459450",
    area: "Gerencia",
    ceco: "María Torres 12",
    estado: "Regular",
  },
  {
    codigo: "20097",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "1.0x1.4x5.4 m",
    serie: "",
    area: "Gerencia",
    ceco: "Daniel León 37",
    estado: "Bueno",
  },
  {
    codigo: "20098",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Madera",
    medidas: "2.5x3.1x3.7 m",
    serie: "",
    area: "Gerencia",
    ceco: "Rosa Mendoza 45",
    estado: "Malo",
  },
  {
    codigo: "20099",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 783",
    color: "Negro",
    material: "",
    medidas: "23'",
    serie: "SN647642737",
    area: "Producción",
    ceco: "Juan Cruz Saldaña 57",
    estado: "Bueno",
  },
  {
    codigo: "20100",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 212",
    color: "Marrón",
    material: "",
    medidas: "17'",
    serie: "SN415729199",
    area: "RRHH",
    ceco: "Miguel Quispe 29",
    estado: "Regular",
  },
  {
    codigo: "20101",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Metal",
    medidas: "2.2x7.3x6.0 m",
    serie: "",
    area: "Gerencia",
    ceco: "María Torres 35",
    estado: "Regular",
  },
  {
    codigo: "20102",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "Sistemas",
    ceco: "Óscar Medina 74",
    estado: "Malo",
  },
  {
    codigo: "20103",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "Producción",
    ceco: "Silvia Benavides",
    estado: "Malo",
  },
  {
    codigo: "20104",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.9x6.1x4.7 m",
    serie: "",
    area: "Administración",
    ceco: "Óscar Medina 1",
    estado: "Regular",
  },
  {
    codigo: "20105",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Mixto",
    medidas: "1.0x7.4x6.1 m",
    serie: "",
    area: "Sistemas",
    ceco: "Lucía Flores 47",
    estado: "Bueno",
  },
  {
    codigo: "20106",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 807",
    color: "Gris",
    material: "",
    medidas: "17'",
    serie: "SN427564509",
    area: "Logística",
    ceco: "Paola Ramos 22",
    estado: "Malo",
  },
  {
    codigo: "20107",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "1.6x5.3x8.1 m",
    serie: "",
    area: "Administración",
    ceco: "Luis Paredes 34",
    estado: "Bueno",
  },
  {
    codigo: "20108",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.2x3.5x6.8 m",
    serie: "",
    area: "Logística",
    ceco: "Lucía Flores 47",
    estado: "Malo",
  },
  {
    codigo: "20109",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 504",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN652483443",
    area: "RRHH",
    ceco: "Lucía Flores 31",
    estado: "Bueno",
  },
  {
    codigo: "20110",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "Producción",
    ceco: "Paola Ramos 22",
    estado: "Bueno",
  },
  {
    codigo: "20111",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Mixto",
    medidas: "1.5x0.9x4.0 m",
    serie: "",
    area: "Logística",
    ceco: "Carlos Rivas 18",
    estado: "Bueno",
  },
  {
    codigo: "20112",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 539",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN468136196",
    area: "Sistemas",
    ceco: "Óscar Medina 1",
    estado: "Bueno",
  },
  {
    codigo: "20113",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 607",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN257280271",
    area: "Administración",
    ceco: "Miguel Quispe 85",
    estado: "Regular",
  },
  {
    codigo: "20114",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Administración",
    ceco: "Pedro Huamán 10",
    estado: "Regular",
  },
  {
    codigo: "20115",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "1.7x3.5x1.0 m",
    serie: "",
    area: "RRHH",
    ceco: "Miguel Quispe 29",
    estado: "Regular",
  },
  {
    codigo: "20116",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "2.9x1.8x8.2 m",
    serie: "",
    area: "Sistemas",
    ceco: "Miguel Quispe 72",
    estado: "Malo",
  },
  {
    codigo: "20117",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 469",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN478318436",
    area: "Gerencia",
    ceco: "Pedro Huamán 14",
    estado: "Malo",
  },
  {
    codigo: "20118",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 266",
    color: "Blanco",
    material: "",
    medidas: "17'",
    serie: "SN449257001",
    area: "Administración",
    ceco: "José Ramírez",
    estado: "Bueno",
  },
  {
    codigo: "20119",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 466",
    color: "Negro",
    material: "",
    medidas: "17'",
    serie: "SN340866312",
    area: "RRHH",
    ceco: "Lucía Flores 31",
    estado: "Bueno",
  },
  {
    codigo: "20120",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 138",
    color: "Marrón",
    material: "",
    medidas: "21'",
    serie: "SN542091021",
    area: "Logística",
    ceco: "Elena Chávez 85",
    estado: "Bueno",
  },
  {
    codigo: "20121",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "1.5x6.3x0.5 m",
    serie: "",
    area: "Gerencia",
    ceco: "Carmen Valdez 92",
    estado: "Malo",
  },
  {
    codigo: "20122",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.3x1.2x6.6 m",
    serie: "",
    area: "Sistemas",
    ceco: "Óscar Medina 74",
    estado: "Malo",
  },
  {
    codigo: "20123",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 837",
    color: "Negro",
    material: "",
    medidas: "23'",
    serie: "SN103565196",
    area: "Logística",
    ceco: "José Ramírez",
    estado: "Regular",
  },
  {
    codigo: "20124",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 245",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN633942772",
    area: "RRHH",
    ceco: "Miguel Quispe 85",
    estado: "Malo",
  },
  {
    codigo: "20125",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "1.0x3.4x4.8 m",
    serie: "",
    area: "Producción",
    ceco: "Elena Chávez 85",
    estado: "Bueno",
  },
  {
    codigo: "20126",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Mixto",
    medidas: "2.6x0.5x7.8 m",
    serie: "",
    area: "RRHH",
    ceco: "Hugo Cárdenas",
    estado: "Regular",
  },
  {
    codigo: "20127",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "2.7x1.6x5.9 m",
    serie: "",
    area: "Gerencia",
    ceco: "Juan Cruz Saldaña 6",
    estado: "Malo",
  },
  {
    codigo: "20128",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Madera",
    medidas: "1.3x2.1x7.5 m",
    serie: "",
    area: "Administración",
    ceco: "Pedro Huamán 14",
    estado: "Bueno",
  },
  {
    codigo: "20129",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Mixto",
    medidas: "1.1x4.2x7.2 m",
    serie: "",
    area: "RRHH",
    ceco: "Miguel Quispe 29",
    estado: "Regular",
  },
  {
    codigo: "20130",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.3x3.5x2.1 m",
    serie: "",
    area: "RRHH",
    ceco: "Carlos Rivas 62",
    estado: "Malo",
  },
  {
    codigo: "20131",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "2.3x2.4x8.7 m",
    serie: "",
    area: "Administración",
    ceco: "Marco Espinoza 33",
    estado: "Regular",
  },
  {
    codigo: "20132",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "Logística",
    ceco: "Lucía Flores 42",
    estado: "Bueno",
  },
  {
    codigo: "20133",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Madera",
    medidas: "1.0x6.0x8.7 m",
    serie: "",
    area: "Sistemas",
    ceco: "José Ramírez",
    estado: "Bueno",
  },
  {
    codigo: "20134",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.1x1.8x8.0 m",
    serie: "",
    area: "Sistemas",
    ceco: "Luis Paredes 34",
    estado: "Regular",
  },
  {
    codigo: "20135",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "Gerencia",
    ceco: "María Torres 12",
    estado: "Malo",
  },
  {
    codigo: "20136",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "1.3x2.0x6.9 m",
    serie: "",
    area: "Gerencia",
    ceco: "Elena Chávez 85",
    estado: "Bueno",
  },
  {
    codigo: "20137",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 972",
    color: "Negro",
    material: "",
    medidas: "27'",
    serie: "SN924359682",
    area: "Logística",
    ceco: "Marco Espinoza 33",
    estado: "Regular",
  },
  {
    codigo: "20138",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "2.4x1.0x1.5 m",
    serie: "",
    area: "Gerencia",
    ceco: "Patricia Silva 46",
    estado: "Regular",
  },
  {
    codigo: "20139",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.8x0.5x1.9 m",
    serie: "",
    area: "Administración",
    ceco: "Marco Espinoza 33",
    estado: "Bueno",
  },
  {
    codigo: "20140",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "1.8x4.0x4.1 m",
    serie: "",
    area: "RRHH",
    ceco: "María Torres 35",
    estado: "Malo",
  },
  {
    codigo: "20141",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 767",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN527420886",
    area: "Administración",
    ceco: "Óscar Medina 1",
    estado: "Malo",
  },
  {
    codigo: "20142",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.4x5.3x2.2 m",
    serie: "",
    area: "Administración",
    ceco: "Norma Aguilar",
    estado: "Malo",
  },
  {
    codigo: "20143",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "2.9x3.2x5.1 m",
    serie: "",
    area: "Logística",
    ceco: "María Torres 12",
    estado: "Malo",
  },
  {
    codigo: "20144",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Mixto",
    medidas: "1.4x0.9x4.2 m",
    serie: "",
    area: "RRHH",
    ceco: "Carlos Rivas 70",
    estado: "Bueno",
  },
  {
    codigo: "20145",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Mixto",
    medidas: "2.5x2.0x7.9 m",
    serie: "",
    area: "Sistemas",
    ceco: "Patricia Silva 9",
    estado: "Malo",
  },
  {
    codigo: "20146",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "Administración",
    ceco: "Juan Cruz Saldaña 6",
    estado: "Bueno",
  },
  {
    codigo: "20147",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 452",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN199000337",
    area: "Logística",
    ceco: "Hugo Cárdenas",
    estado: "Regular",
  },
  {
    codigo: "20148",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 293",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN807810745",
    area: "RRHH",
    ceco: "Pedro Huamán 14",
    estado: "Regular",
  },
  {
    codigo: "20149",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Madera",
    medidas: "1.6x6.6x5.2 m",
    serie: "",
    area: "Sistemas",
    ceco: "Rosa Mendoza 45",
    estado: "Regular",
  },
  {
    codigo: "20150",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.3x2.9x2.0 m",
    serie: "",
    area: "Producción",
    ceco: "Rosa Mendoza 45",
    estado: "Bueno",
  },
  {
    codigo: "20151",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 529",
    color: "Blanco",
    material: "",
    medidas: "21'",
    serie: "SN130894368",
    area: "Administración",
    ceco: "Rosa Mendoza 45",
    estado: "Bueno",
  },
  {
    codigo: "20152",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 653",
    color: "Blanco",
    material: "",
    medidas: "26'",
    serie: "SN850115845",
    area: "RRHH",
    ceco: "Miguel Quispe 29",
    estado: "Regular",
  },
  {
    codigo: "20153",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 497",
    color: "Blanco",
    material: "",
    medidas: "23'",
    serie: "SN389744597",
    area: "Gerencia",
    ceco: "Carmen Valdez 92",
    estado: "Malo",
  },
  {
    codigo: "20154",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "2.8x5.6x2.6 m",
    serie: "",
    area: "Administración",
    ceco: "Miguel Quispe 85",
    estado: "Bueno",
  },
  {
    codigo: "20155",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "1.4x1.2x0.7 m",
    serie: "",
    area: "Sistemas",
    ceco: "Luis Paredes 34",
    estado: "Malo",
  },
  {
    codigo: "20156",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "1.4x7.5x2.5 m",
    serie: "",
    area: "Producción",
    ceco: "Paola Ramos 22",
    estado: "Malo",
  },
  {
    codigo: "20157",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 828",
    color: "Gris",
    material: "",
    medidas: "22'",
    serie: "SN879350686",
    area: "RRHH",
    ceco: "Miguel Quispe 85",
    estado: "Malo",
  },
  {
    codigo: "20158",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 504",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN498054763",
    area: "Administración",
    ceco: "Juan Cruz Saldaña 57",
    estado: "Bueno",
  },
  {
    codigo: "20159",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "Sistemas",
    ceco: "Lucía Flores 47",
    estado: "Malo",
  },
  {
    codigo: "20160",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "1.5x2.0x3.2 m",
    serie: "",
    area: "Sistemas",
    ceco: "Carlos Rivas 70",
    estado: "Bueno",
  },
  {
    codigo: "20161",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 889",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN260363364",
    area: "Logística",
    ceco: "Luis Paredes 34",
    estado: "Malo",
  },
  {
    codigo: "20162",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.4x7.8x5.5 m",
    serie: "",
    area: "Gerencia",
    ceco: "Carlos Rivas 70",
    estado: "Malo",
  },
  {
    codigo: "20163",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 603",
    color: "Negro",
    material: "",
    medidas: "14'",
    serie: "SN418701845",
    area: "Administración",
    ceco: "Miguel Quispe 29",
    estado: "Regular",
  },
  {
    codigo: "20164",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "1.3x6.4x6.2 m",
    serie: "",
    area: "Administración",
    ceco: "Pedro Huamán 14",
    estado: "Regular",
  },
  {
    codigo: "20165",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 394",
    color: "Marrón",
    material: "",
    medidas: "18'",
    serie: "SN580819925",
    area: "Administración",
    ceco: "Ana Gómez 57",
    estado: "Malo",
  },
  {
    codigo: "20166",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "2.2x4.2x3.7 m",
    serie: "",
    area: "Sistemas",
    ceco: "Carlos Rivas 62",
    estado: "Malo",
  },
  {
    codigo: "20167",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 426",
    color: "Blanco",
    material: "",
    medidas: "21'",
    serie: "SN810403505",
    area: "RRHH",
    ceco: "Óscar Medina 74",
    estado: "Bueno",
  },
  {
    codigo: "20168",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 126",
    color: "Negro",
    material: "",
    medidas: "20'",
    serie: "SN911102052",
    area: "RRHH",
    ceco: "Elena Chávez 85",
    estado: "Regular",
  },
  {
    codigo: "20169",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 412",
    color: "Negro",
    material: "",
    medidas: "18'",
    serie: "SN843674996",
    area: "Administración",
    ceco: "Lucía Flores 42",
    estado: "Malo",
  },
  {
    codigo: "20170",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "2.1x6.7x2.9 m",
    serie: "",
    area: "Logística",
    ceco: "Carlos Rivas 62",
    estado: "Regular",
  },
  {
    codigo: "20171",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Mixto",
    medidas: "2.7x0.3x1.5 m",
    serie: "",
    area: "RRHH",
    ceco: "Carmen Valdez 92",
    estado: "Bueno",
  },
  {
    codigo: "20172",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 718",
    color: "Gris",
    material: "",
    medidas: "27'",
    serie: "SN225172670",
    area: "RRHH",
    ceco: "Ricardo Núñez 64",
    estado: "Bueno",
  },
  {
    codigo: "20173",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "2.5x5.6x6.0 m",
    serie: "",
    area: "RRHH",
    ceco: "Lucía Flores 42",
    estado: "Bueno",
  },
  {
    codigo: "20174",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Logística",
    ceco: "María Torres 12",
    estado: "Regular",
  },
  {
    codigo: "20175",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Mixto",
    medidas: "1.0x6.6x8.5 m",
    serie: "",
    area: "Administración",
    ceco: "Óscar Medina 1",
    estado: "Bueno",
  },
  {
    codigo: "20176",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 576",
    color: "Negro",
    material: "",
    medidas: "26'",
    serie: "SN605952786",
    area: "RRHH",
    ceco: "Lucía Flores 47",
    estado: "Regular",
  },
  {
    codigo: "20177",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Sistemas",
    ceco: "Lucía Flores 42",
    estado: "Regular",
  },
  {
    codigo: "20178",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 362",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN827378429",
    area: "Producción",
    ceco: "Pedro Huamán 14",
    estado: "Malo",
  },
  {
    codigo: "20179",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.9x5.4x0.3 m",
    serie: "",
    area: "Administración",
    ceco: "Patricia Silva 46",
    estado: "Malo",
  },
  {
    codigo: "20180",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Metal",
    medidas: "2.8x7.5x8.3 m",
    serie: "",
    area: "RRHH",
    ceco: "Elena Chávez 85",
    estado: "Malo",
  },
  {
    codigo: "20181",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Madera",
    medidas: "1.7x7.4x5.1 m",
    serie: "",
    area: "Sistemas",
    ceco: "Carlos Rivas 18",
    estado: "Malo",
  },
  {
    codigo: "20182",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 309",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN593046628",
    area: "Sistemas",
    ceco: "Patricia Silva 9",
    estado: "Regular",
  },
  {
    codigo: "20183",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "2.2x5.1x5.4 m",
    serie: "",
    area: "Logística",
    ceco: "Óscar Medina 1",
    estado: "Regular",
  },
  {
    codigo: "20184",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Mixto",
    medidas: "1.4x7.3x5.8 m",
    serie: "",
    area: "Producción",
    ceco: "Daniel León 37",
    estado: "Bueno",
  },
  {
    codigo: "20185",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 563",
    color: "Negro",
    material: "",
    medidas: "25'",
    serie: "SN622631868",
    area: "RRHH",
    ceco: "Daniel León 37",
    estado: "Malo",
  },
  {
    codigo: "20186",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Madera",
    medidas: "2.8x5.4x7.1 m",
    serie: "",
    area: "RRHH",
    ceco: "Lucía Flores 42",
    estado: "Malo",
  },
  {
    codigo: "20187",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Administración",
    ceco: "Lucía Flores 42",
    estado: "Regular",
  },
  {
    codigo: "20188",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "1.7x6.0x0.1 m",
    serie: "",
    area: "Sistemas",
    ceco: "María Torres 35",
    estado: "Bueno",
  },
  {
    codigo: "20189",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 277",
    color: "Marrón",
    material: "",
    medidas: "17'",
    serie: "SN374080793",
    area: "Producción",
    ceco: "José Ramírez",
    estado: "Malo",
  },
  {
    codigo: "20190",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 839",
    color: "Gris",
    material: "",
    medidas: "17'",
    serie: "SN265878273",
    area: "Producción",
    ceco: "Paola Ramos 22",
    estado: "Bueno",
  },
  {
    codigo: "20191",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 430",
    color: "Marrón",
    material: "",
    medidas: "26'",
    serie: "SN157257641",
    area: "Logística",
    ceco: "Daniel León 37",
    estado: "Bueno",
  },
  {
    codigo: "20192",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 509",
    color: "Gris",
    material: "",
    medidas: "19'",
    serie: "SN626653346",
    area: "RRHH",
    ceco: "Carlos Rivas 18",
    estado: "Bueno",
  },
  {
    codigo: "20193",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Mixto",
    medidas: "2.7x3.0x4.6 m",
    serie: "",
    area: "Logística",
    ceco: "María Torres 12",
    estado: "Bueno",
  },
  {
    codigo: "20194",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 692",
    color: "Marrón",
    material: "",
    medidas: "18'",
    serie: "SN376004041",
    area: "Logística",
    ceco: "Marco Espinoza 33",
    estado: "Bueno",
  },
  {
    codigo: "20195",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 276",
    color: "Negro",
    material: "",
    medidas: "26'",
    serie: "SN496553231",
    area: "Gerencia",
    ceco: "Carmen Valdez 92",
    estado: "Bueno",
  },
  {
    codigo: "20196",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 308",
    color: "Blanco",
    material: "",
    medidas: "25'",
    serie: "SN907588637",
    area: "Sistemas",
    ceco: "Pedro Huamán 10",
    estado: "Regular",
  },
  {
    codigo: "20197",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Mixto",
    medidas: "1.2x4.9x5.2 m",
    serie: "",
    area: "Sistemas",
    ceco: "Óscar Medina 1",
    estado: "Malo",
  },
  {
    codigo: "20198",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "2.8x2.3x8.1 m",
    serie: "",
    area: "Logística",
    ceco: "Daniel León 37",
    estado: "Malo",
  },
  {
    codigo: "20199",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 733",
    color: "Negro",
    material: "",
    medidas: "24'",
    serie: "SN532503901",
    area: "Gerencia",
    ceco: "Ana Gómez 57",
    estado: "Bueno",
  },
  {
    codigo: "20200",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 779",
    color: "Negro",
    material: "",
    medidas: "23'",
    serie: "SN964799541",
    area: "Logística",
    ceco: "Carmen Valdez 92",
    estado: "Regular",
  },
  {
    codigo: "20201",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Madera",
    medidas: "1.2x0.3x3.2 m",
    serie: "",
    area: "Producción",
    ceco: "Óscar Medina 1",
    estado: "Regular",
  },
  {
    codigo: "20202",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.7x4.3x4.9 m",
    serie: "",
    area: "Gerencia",
    ceco: "Patricia Silva 46",
    estado: "Bueno",
  },
  {
    codigo: "20203",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 422",
    color: "Marrón",
    material: "",
    medidas: "17'",
    serie: "SN734152375",
    area: "Producción",
    ceco: "Ana Gómez 57",
    estado: "Bueno",
  },
  {
    codigo: "20204",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 923",
    color: "Negro",
    material: "",
    medidas: "19'",
    serie: "SN814226483",
    area: "Producción",
    ceco: "Ana Gómez 57",
    estado: "Bueno",
  },
  {
    codigo: "20205",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "1.9x4.4x3.6 m",
    serie: "",
    area: "Producción",
    ceco: "Lucía Flores 42",
    estado: "Malo",
  },
  {
    codigo: "20206",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Mixto",
    medidas: "1.3x6.8x1.2 m",
    serie: "",
    area: "Administración",
    ceco: "Silvia Benavides",
    estado: "Regular",
  },
  {
    codigo: "20207",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 255",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN394353979",
    area: "Gerencia",
    ceco: "María Torres 12",
    estado: "Bueno",
  },
  {
    codigo: "20208",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "2.8x1.7x8.4 m",
    serie: "",
    area: "Producción",
    ceco: "Pedro Huamán 14",
    estado: "Malo",
  },
  {
    codigo: "20209",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 329",
    color: "Blanco",
    material: "",
    medidas: "18'",
    serie: "SN900680169",
    area: "Sistemas",
    ceco: "Hugo Cárdenas",
    estado: "Malo",
  },
  {
    codigo: "20210",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Madera",
    medidas: "2.3x3.8x4.3 m",
    serie: "",
    area: "RRHH",
    ceco: "Miguel Quispe 72",
    estado: "Malo",
  },
  {
    codigo: "20211",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 466",
    color: "Gris",
    material: "",
    medidas: "23'",
    serie: "SN164558841",
    area: "Gerencia",
    ceco: "Daniel León 37",
    estado: "Malo",
  },
  {
    codigo: "20212",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Mixto",
    medidas: "2.9x0.7x7.7 m",
    serie: "",
    area: "Logística",
    ceco: "Elena Chávez 85",
    estado: "Malo",
  },
  {
    codigo: "20213",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "RRHH",
    ceco: "Carlos Rivas 18",
    estado: "Bueno",
  },
  {
    codigo: "20214",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Metal",
    medidas: "2.8x5.3x3.3 m",
    serie: "",
    area: "Sistemas",
    ceco: "Daniel León 29",
    estado: "Regular",
  },
  {
    codigo: "20215",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.8x7.4x3.6 m",
    serie: "",
    area: "Producción",
    ceco: "Juan Cruz Saldaña 6",
    estado: "Bueno",
  },
  {
    codigo: "20216",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Metal",
    medidas: "1.9x1.4x1.2 m",
    serie: "",
    area: "Logística",
    ceco: "Carlos Rivas 62",
    estado: "Regular",
  },
  {
    codigo: "20217",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Madera",
    medidas: "2.4x5.0x4.0 m",
    serie: "",
    area: "Administración",
    ceco: "Daniel León 37",
    estado: "Bueno",
  },
  {
    codigo: "20218",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 247",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN482874992",
    area: "Logística",
    ceco: "Pedro Huamán 10",
    estado: "Regular",
  },
  {
    codigo: "20219",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Metal",
    medidas: "",
    serie: "",
    area: "Logística",
    ceco: "Juan Cruz Saldaña 6",
    estado: "Bueno",
  },
  {
    codigo: "20220",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "2.3x2.5x6.9 m",
    serie: "",
    area: "Administración",
    ceco: "Juan Cruz Saldaña 57",
    estado: "Malo",
  },
  {
    codigo: "20221",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "1.6x3.3x0.4 m",
    serie: "",
    area: "Logística",
    ceco: "Pedro Huamán 10",
    estado: "Bueno",
  },
  {
    codigo: "20222",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "2.7x6.3x5.3 m",
    serie: "",
    area: "Logística",
    ceco: "Daniel León 37",
    estado: "Regular",
  },
  {
    codigo: "20223",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "1.2x4.0x4.5 m",
    serie: "",
    area: "Gerencia",
    ceco: "Óscar Medina 1",
    estado: "Bueno",
  },
  {
    codigo: "20224",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 507",
    color: "Gris",
    material: "",
    medidas: "25'",
    serie: "SN622775302",
    area: "RRHH",
    ceco: "Rosa Mendoza 45",
    estado: "Malo",
  },
  {
    codigo: "20225",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Madera",
    medidas: "1.6x4.6x4.3 m",
    serie: "",
    area: "Sistemas",
    ceco: "Carlos Rivas 18",
    estado: "Bueno",
  },
  {
    codigo: "20226",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "1.9x1.8x2.6 m",
    serie: "",
    area: "Gerencia",
    ceco: "Hugo Cárdenas",
    estado: "Regular",
  },
  {
    codigo: "20227",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 169",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN411196962",
    area: "Logística",
    ceco: "Óscar Medina 74",
    estado: "Bueno",
  },
  {
    codigo: "20228",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "2.3x6.4x2.4 m",
    serie: "",
    area: "Administración",
    ceco: "Juan Cruz Saldaña 6",
    estado: "Malo",
  },
  {
    codigo: "20229",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 506",
    color: "Blanco",
    material: "",
    medidas: "26'",
    serie: "SN897444880",
    area: "Logística",
    ceco: "Lucía Flores 47",
    estado: "Bueno",
  },
  {
    codigo: "20230",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 654",
    color: "Marrón",
    material: "",
    medidas: "27'",
    serie: "SN978529553",
    area: "Administración",
    ceco: "Óscar Medina 74",
    estado: "Regular",
  },
  {
    codigo: "20231",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 729",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN120063977",
    area: "RRHH",
    ceco: "Miguel Quispe 72",
    estado: "Regular",
  },
  {
    codigo: "20232",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 373",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN651521881",
    area: "Sistemas",
    ceco: "Paola Ramos 22",
    estado: "Bueno",
  },
  {
    codigo: "20233",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "Sistemas",
    ceco: "Miguel Quispe 85",
    estado: "Malo",
  },
  {
    codigo: "20234",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 412",
    color: "Gris",
    material: "",
    medidas: "22'",
    serie: "SN219809020",
    area: "RRHH",
    ceco: "Rosa Mendoza 45",
    estado: "Malo",
  },
  {
    codigo: "20235",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 162",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN868573520",
    area: "RRHH",
    ceco: "Daniel León 29",
    estado: "Bueno",
  },
  {
    codigo: "20236",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "2.1x5.6x1.2 m",
    serie: "",
    area: "Gerencia",
    ceco: "Marco Espinoza 33",
    estado: "Regular",
  },
  {
    codigo: "20237",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Madera",
    medidas: "1.4x6.1x0.1 m",
    serie: "",
    area: "Administración",
    ceco: "Pedro Huamán 14",
    estado: "Bueno",
  },
  {
    codigo: "20238",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Mixto",
    medidas: "1.2x6.3x6.7 m",
    serie: "",
    area: "Administración",
    ceco: "Miguel Quispe 85",
    estado: "Regular",
  },
  {
    codigo: "20239",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 386",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN786071326",
    area: "Sistemas",
    ceco: "Patricia Silva 9",
    estado: "Regular",
  },
  {
    codigo: "20240",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "1.0x6.0x6.7 m",
    serie: "",
    area: "Logística",
    ceco: "Lucía Flores 31",
    estado: "Regular",
  },
  {
    codigo: "20241",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 200",
    color: "Blanco",
    material: "",
    medidas: "21'",
    serie: "SN206494608",
    area: "Gerencia",
    ceco: "Juan Cruz Saldaña 57",
    estado: "Regular",
  },
  {
    codigo: "20242",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 820",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN849200964",
    area: "Producción",
    ceco: "Pedro Huamán 14",
    estado: "Malo",
  },
  {
    codigo: "20243",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 883",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN263881240",
    area: "Sistemas",
    ceco: "Pedro Huamán 14",
    estado: "Malo",
  },
  {
    codigo: "20244",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 285",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN497459590",
    area: "Logística",
    ceco: "Pedro Huamán 10",
    estado: "Malo",
  },
  {
    codigo: "20245",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 702",
    color: "Gris",
    material: "",
    medidas: "17'",
    serie: "SN743976452",
    area: "RRHH",
    ceco: "Ricardo Núñez 64",
    estado: "Malo",
  },
  {
    codigo: "20246",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 133",
    color: "Negro",
    material: "",
    medidas: "14'",
    serie: "SN931927241",
    area: "Producción",
    ceco: "Daniel León 37",
    estado: "Bueno",
  },
  {
    codigo: "20247",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "2.0x2.3x4.5 m",
    serie: "",
    area: "Sistemas",
    ceco: "Lucía Flores 42",
    estado: "Regular",
  },
  {
    codigo: "20248",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 213",
    color: "Gris",
    material: "",
    medidas: "21'",
    serie: "SN339895020",
    area: "Administración",
    ceco: "Elena Chávez 85",
    estado: "Bueno",
  },
  {
    codigo: "20249",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "1.9x1.1x0.2 m",
    serie: "",
    area: "Logística",
    ceco: "Silvia Benavides",
    estado: "Regular",
  },
  {
    codigo: "20250",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 937",
    color: "Gris",
    material: "",
    medidas: "20'",
    serie: "SN311586608",
    area: "Logística",
    ceco: "Rosa Mendoza 45",
    estado: "Bueno",
  },
  {
    codigo: "20251",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Metal",
    medidas: "2.7x5.6x0.8 m",
    serie: "",
    area: "Administración",
    ceco: "Norma Aguilar",
    estado: "Regular",
  },
  {
    codigo: "20252",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 909",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN517950245",
    area: "Gerencia",
    ceco: "Lucía Flores 31",
    estado: "Malo",
  },
  {
    codigo: "20253",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Sistemas",
    ceco: "Andrea Ruiz 20",
    estado: "Regular",
  },
  {
    codigo: "20254",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 939",
    color: "Gris",
    material: "",
    medidas: "23'",
    serie: "SN476850677",
    area: "Administración",
    ceco: "Norma Aguilar",
    estado: "Malo",
  },
  {
    codigo: "20255",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 926",
    color: "Marrón",
    material: "",
    medidas: "17'",
    serie: "SN992400141",
    area: "RRHH",
    ceco: "Lucía Flores 47",
    estado: "Bueno",
  },
  {
    codigo: "20256",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 658",
    color: "Negro",
    material: "",
    medidas: "20'",
    serie: "SN532516041",
    area: "RRHH",
    ceco: "Miguel Quispe 72",
    estado: "Regular",
  },
  {
    codigo: "20257",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Administración",
    ceco: "Andrea Ruiz 20",
    estado: "Regular",
  },
  {
    codigo: "20258",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "1.1x5.2x7.6 m",
    serie: "",
    area: "RRHH",
    ceco: "Juan Cruz Saldaña 57",
    estado: "Malo",
  },
  {
    codigo: "20259",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 471",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN953711562",
    area: "Gerencia",
    ceco: "Lucía Flores 47",
    estado: "Bueno",
  },
  {
    codigo: "20260",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 545",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN930871460",
    area: "RRHH",
    ceco: "Ricardo Núñez 64",
    estado: "Malo",
  },
  {
    codigo: "20261",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Mixto",
    medidas: "1.5x7.4x8.0 m",
    serie: "",
    area: "Logística",
    ceco: "Luis Paredes 34",
    estado: "Bueno",
  },
  {
    codigo: "20262",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 465",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN831806813",
    area: "Sistemas",
    ceco: "Andrea Ruiz 20",
    estado: "Bueno",
  },
  {
    codigo: "20263",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 137",
    color: "Marrón",
    material: "",
    medidas: "18'",
    serie: "SN549120583",
    area: "Gerencia",
    ceco: "Miguel Quispe 85",
    estado: "Bueno",
  },
  {
    codigo: "20264",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 996",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN762446422",
    area: "Sistemas",
    ceco: "Óscar Medina 1",
    estado: "Malo",
  },
  {
    codigo: "20265",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 565",
    color: "Blanco",
    material: "",
    medidas: "",
    serie: "SN764880054",
    area: "Administración",
    ceco: "Hugo Cárdenas",
    estado: "Bueno",
  },
  {
    codigo: "20266",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 806",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN513072240",
    area: "RRHH",
    ceco: "Daniel León 37",
    estado: "Regular",
  },
  {
    codigo: "20267",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "HP",
    modelo: "Model 684",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN492480630",
    area: "Logística",
    ceco: "José Ramírez",
    estado: "Bueno",
  },
  {
    codigo: "20268",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 523",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN595951919",
    area: "Administración",
    ceco: "Andrea Ruiz 20",
    estado: "Bueno",
  },
  {
    codigo: "20269",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Mixto",
    medidas: "1.0x0.2x1.1 m",
    serie: "",
    area: "Sistemas",
    ceco: "Patricia Silva 46",
    estado: "Bueno",
  },
  {
    codigo: "20270",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 544",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN634846469",
    area: "Administración",
    ceco: "Carlos Rivas 62",
    estado: "Bueno",
  },
  {
    codigo: "20271",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 429",
    color: "Blanco",
    material: "",
    medidas: "23'",
    serie: "SN441941582",
    area: "Gerencia",
    ceco: "Carmen Valdez 92",
    estado: "Regular",
  },
  {
    codigo: "20272",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Marrón",
    material: "Madera",
    medidas: "2.5x2.3x4.3 m",
    serie: "",
    area: "Logística",
    ceco: "Luis Paredes 34",
    estado: "Bueno",
  },
  {
    codigo: "20273",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 511",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN710867665",
    area: "Gerencia",
    ceco: "Lucía Flores 47",
    estado: "Regular",
  },
  {
    codigo: "20274",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 411",
    color: "Gris",
    material: "",
    medidas: "22'",
    serie: "SN196249604",
    area: "RRHH",
    ceco: "Andrea Ruiz 20",
    estado: "Malo",
  },
  {
    codigo: "20275",
    descripcion: "Escritorio",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Madera",
    medidas: "1.5x0.0x5.1 m",
    serie: "",
    area: "Gerencia",
    ceco: "Ricardo Núñez 64",
    estado: "Regular",
  },
  {
    codigo: "20276",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "1.2x0.8x8.9 m",
    serie: "",
    area: "Logística",
    ceco: "María Torres 35",
    estado: "Malo",
  },
  {
    codigo: "20277",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "2.6x3.2x4.1 m",
    serie: "",
    area: "Logística",
    ceco: "Daniel León 37",
    estado: "Bueno",
  },
  {
    codigo: "20278",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Madera",
    medidas: "",
    serie: "",
    area: "Gerencia",
    ceco: "Óscar Medina 74",
    estado: "Bueno",
  },
  {
    codigo: "20279",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 264",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN965448854",
    area: "Gerencia",
    ceco: "Juan Cruz Saldaña 57",
    estado: "Malo",
  },
  {
    codigo: "20280",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Madera",
    medidas: "2.3x4.8x2.6 m",
    serie: "",
    area: "Gerencia",
    ceco: "Patricia Silva 9",
    estado: "Regular",
  },
  {
    codigo: "20281",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 583",
    color: "Marrón",
    material: "",
    medidas: "19'",
    serie: "SN407741138",
    area: "Sistemas",
    ceco: "Silvia Benavides",
    estado: "Malo",
  },
  {
    codigo: "20282",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 611",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN509189446",
    area: "Logística",
    ceco: "Ricardo Núñez 64",
    estado: "Malo",
  },
  {
    codigo: "20283",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 822",
    color: "Gris",
    material: "",
    medidas: "",
    serie: "SN696655295",
    area: "RRHH",
    ceco: "Elena Chávez 85",
    estado: "Bueno",
  },
  {
    codigo: "20284",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 663",
    color: "Blanco",
    material: "",
    medidas: "26'",
    serie: "SN715021503",
    area: "Gerencia",
    ceco: "Marco Espinoza 33",
    estado: "Regular",
  },
  {
    codigo: "20285",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Genérico",
    modelo: "Model 919",
    color: "Gris",
    material: "",
    medidas: "17'",
    serie: "SN228721886",
    area: "Administración",
    ceco: "Daniel León 29",
    estado: "Bueno",
  },
  {
    codigo: "20286",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Lenovo",
    modelo: "Model 954",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN193038914",
    area: "RRHH",
    ceco: "María Torres 35",
    estado: "Malo",
  },
  {
    codigo: "20287",
    descripcion: "Monitor",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 598",
    color: "Blanco",
    material: "",
    medidas: "21'",
    serie: "SN185176058",
    area: "Logística",
    ceco: "Lucía Flores 42",
    estado: "Bueno",
  },
  {
    codigo: "20288",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "Producción",
    ceco: "Carlos Rivas 70",
    estado: "Bueno",
  },
  {
    codigo: "20289",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 131",
    color: "Gris",
    material: "",
    medidas: "25'",
    serie: "SN826115458",
    area: "Logística",
    ceco: "María Torres 12",
    estado: "Bueno",
  },
  {
    codigo: "20290",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Dell",
    modelo: "Model 426",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN682075347",
    area: "Administración",
    ceco: "Lucía Flores 47",
    estado: "Bueno",
  },
  {
    codigo: "20291",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "RRHH",
    ceco: "Miguel Quispe 85",
    estado: "Regular",
  },
  {
    codigo: "20292",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Metal",
    medidas: "2.8x0.7x6.9 m",
    serie: "",
    area: "Gerencia",
    ceco: "Norma Aguilar",
    estado: "Bueno",
  },
  {
    codigo: "20293",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "LG",
    modelo: "Model 902",
    color: "Marrón",
    material: "",
    medidas: "",
    serie: "SN259809940",
    area: "Logística",
    ceco: "Lucía Flores 47",
    estado: "Bueno",
  },
  {
    codigo: "20294",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "1.3x4.4x3.9 m",
    serie: "",
    area: "RRHH",
    ceco: "Elena Chávez 85",
    estado: "Regular",
  },
  {
    codigo: "20295",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Blanco",
    material: "Mixto",
    medidas: "1.9x3.2x0.6 m",
    serie: "",
    area: "Producción",
    ceco: "Víctor Palacios",
    estado: "Malo",
  },
  {
    codigo: "20296",
    descripcion: "Impresora",
    categoria: "Equipo",
    marca: "Epson",
    modelo: "Model 492",
    color: "Negro",
    material: "",
    medidas: "",
    serie: "SN130066963",
    area: "Administración",
    ceco: "Carlos Rivas 62",
    estado: "Malo",
  },
  {
    codigo: "20297",
    descripcion: "Laptop",
    categoria: "Equipo",
    marca: "Samsung",
    modelo: "Model 637",
    color: "Gris",
    material: "",
    medidas: "15'",
    serie: "SN190316783",
    area: "Gerencia",
    ceco: "Ricardo Núñez 64",
    estado: "Regular",
  },
  {
    codigo: "20298",
    descripcion: "Silla",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Gris",
    material: "Metal",
    medidas: "2.6x0.5x6.0 m",
    serie: "",
    area: "Producción",
    ceco: "Carlos Rivas 70",
    estado: "Malo",
  },
  {
    codigo: "20299",
    descripcion: "Anaquel",
    categoria: "Mobiliario",
    marca: "",
    modelo: "",
    color: "Negro",
    material: "Metal",
    medidas: "2.4x4.3x5.2 m",
    serie: "",
    area: "Gerencia",
    ceco: "Rosa Mendoza 45",
    estado: "Malo",
  },
  {
    codigo: "20300",
    descripcion: "Teclado",
    categoria: "Accesorio",
    marca: "",
    modelo: "",
    color: "",
    material: "Mixto",
    medidas: "",
    serie: "",
    area: "Sistemas",
    ceco: "Daniel León 29",
    estado: "Bueno",
  },
];
